### ISSUE TITLE
Link to McGrawHill page is broken

### ISSUE THREAD

**Issue by lbaute** [LGP5/Resources#12]
The link on github LGP5 About Section on Resources  Repo page is broken...

It links to
https://www.mhprofessional.com/9781260135268-usa-labview-graphical-programming-fifth-edition-group
New link is
https://www.mhprofessional.com/labview-graphical-programming-fifth-edition-9781260135268-usa

Im not sure if its related to where in the world you open it, I click on it in MI, US

**Comment by unifab** [comment]
Thanks for the heads-up, I fixed it on the about section and on the Readme as well.

Thank you!
